name: Windows ARM Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-pc-windows-msvc
    
    - name: Check Rust installation
      run: |
        rustc --version
        cargo --version
        rustup show
    
    - name: Build
      run: cargo build --release --target aarch64-pc-windows-msvc
    
    - name: List artifacts
      run: |
        Get-ChildItem -Path target/aarch64-pc-windows-msvc/release/ -Filter *.exe
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-arm-binary
        path: target/aarch64-pc-windows-msvc/release/*.exe
        if-no-files-found: error